### ISSUE TITLE
Create detailed work plan with indicators, timeframes and deliverables -  SARAdatascraping

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/saraDataScraping#3]
### Proposed Change/Activity
Create a detailed work plan for this project.  The workplan should include clear indicators, timelines, and deliverables. The project proposal with initial deliverables and timelines can be found in the [Project Planning Tool](http://dmapps/en/ppt/projects/2134/view/)

### Why is this important
The discussions made when crafting the project proposal created a high level overview of a work plan and a more detailed version is necessary enable efficient workflows.  Additionally, the project is starting later than originally planned which will require modifying  the initial timelines around deliverables. 

### Additional Context
Any workplan should be discussed and approved by the project committee.

### Actions
- [ ] Clearly define the final deliverables
- [ ] Create key tickets in quarterly milestones
- [ ] Identify any possible indicators to include

**Comment by stoyelq** [comment]
Final deliverables indicated in the project proposal and in Readme (amongst other places) workplan will be incremental based off of SARA needs and Scrum meetings.
